import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.scss";
import "./styles/page.module.scss";

import Header from './components/header';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Event Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Header />

        {children}
        
      </body>
    </html>
  );
}
